b1: 0.8947
b2: 0.999
competition_mode: false
dataset_name: cifar_anon
ensemble_size: 2
keep_best_weights: true
lr: 0.0009332
method: ensemble
min_lr: 5.5e-06
nb_epochs: 100
normalize: false
optimizer: adam
save_dir: cifar_anon_ensemble_200
test_batch_size: 256
train_batch_size: 86
train_val_split: true
