dataset_name: cifar_anon
method: sequential_ensemble
train_batch_size: 86
test_batch_size: 256
nb_epochs: 2
optimizer: "adam"
lr: 0.0009332
min_lr: 0.0000055
num_workers: 4
save_dir: cifar_anon_sequential_ensemble_test
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8947
b2: 0.999
train_val_split: True
ensemble_size: 2
num_chains: 1
sequential_nb_epochs: 1
sequential_optimizer: adam
sequential_b1: 0.8731
sequential_b2: 0.998
sequential_lr: 0.0023
sequential_min_lr: 0.0000539
sampler: guided_walk
step_std: 0.02
imbalance: False
normalize: False
competition_mode: False
