b1: 0.8947
b2: 0.999
competition_mode: false
dataset_name: cifar_anon
ensemble_size: 2
keep_best_weights: true
lr: 0.0009332
method: sequential_ensemble
min_lr: 5.5e-06
nb_epochs: 2
normalize: false
num_chains: 1
optimizer: adam
sampler: guided_walk
save_dir: cifar_anon_sequential_ensemble_test
sequential_b1: 0.8731
sequential_b2: 0.998
sequential_lr: 0.0023
sequential_min_lr: 5.39e-05
sequential_nb_epochs: 1
sequential_optimizer: adam
step_std: 0.02
test_batch_size: 256
train_batch_size: 86
train_val_split: true
