dataset_name: cifar_anon
method: ensemble
train_batch_size: 86
test_batch_size: 256
nb_epochs: 100
optimizer: "adam"
lr: 0.0009332
min_lr: 0.0000055
num_workers: 4
save_dir: cifar_anon_ensemble_1000
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8947
b2: 0.999
train_val_split: True
ensemble_size: 10
imbalance: False
normalize: False
competition_mode: False
