b1: 0.8921
b2: 0.9962
competition_mode: false
dataset_name: energy_anon
ensemble_size: 100
keep_best_weights: true
lr: 0.008989
method: ensemble
min_lr: 4.83e-05
nb_epochs: 100
normalize: false
optimizer: adam
save_dir: energy_anon_ensemble_10000
test_batch_size: 256
train_batch_size: 58
train_val_split: true
