dataset_name: energy_anon
method: ensemble
train_batch_size: 58
test_batch_size: 256
nb_epochs: 100
optimizer: "adam"
lr: 0.008989
min_lr: 0.0000483
num_workers: 4
save_dir: energy_anon_ensemble_10000
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8921
b2: 0.9962
train_val_split: True
ensemble_size: 100
imbalance: False
normalize: False
competition_mode: False
