dataset_name: energy_anon
method: sequential_ensemble
train_batch_size: 58
test_batch_size: 256
nb_epochs: 2
optimizer: "adam"
lr: 0.008989
min_lr: 0.0000483
num_workers: 4
save_dir: energy_anon_sequential_ensemble_test
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8921
b2: 0.9962
train_val_split: True
ensemble_size: 2
num_chains: 1
sequential_nb_epochs: 1
sequential_optimizer: adam
sequential_b1: 0.8109
sequential_b2: 0.9959
sequential_lr: 0.002724
sequential_min_lr: 0.0001518
sampler: guided_walk
step_std: 0.01
imbalance: False
normalize: False
competition_mode: False
