b1: 0.8921
b2: 0.9962
competition_mode: false
dataset_name: energy_anon
ensemble_size: 2
keep_best_weights: true
lr: 0.008989
method: sequential_ensemble
min_lr: 4.83e-05
nb_epochs: 2
normalize: false
num_chains: 1
optimizer: adam
sampler: guided_walk
save_dir: energy_anon_sequential_ensemble_test
sequential_b1: 0.8109
sequential_b2: 0.9959
sequential_lr: 0.002724
sequential_min_lr: 0.0001518
sequential_nb_epochs: 1
sequential_optimizer: adam
step_std: 0.01
test_batch_size: 256
train_batch_size: 58
train_val_split: true
