b1: 0.8866
b2: 0.9989
competition_mode: false
dataset_name: imdb
ensemble_size: 50
keep_best_weights: true
lr: 0.0007436
method: sequential_ensemble
min_lr: 0.000282
nb_epochs: 100
normalize: false
num_chains: 1
optimizer: adam
sampler: guided_walk
save_dir: imdb_sequential_ensemble_200
sequential_b1: 0.8961
sequential_b2: 0.9994
sequential_lr: 0.002392
sequential_min_lr: 1.43e-05
sequential_nb_epochs: 2
sequential_optimizer: adam
step_std: 0.02
test_batch_size: 256
train_batch_size: 141
train_val_split: true
