b1: 0.8866
b2: 0.9989
competition_mode: false
dataset_name: imdb
ensemble_size: 2
keep_best_weights: true
lr: 0.0007436
method: ensemble
min_lr: 0.000282
nb_epochs: 100
normalize: false
optimizer: adam
save_dir: imdb_ensemble_200
test_batch_size: 256
train_batch_size: 141
train_val_split: true
