dataset_name: imdb
method: sequential_ensemble
train_batch_size: 141
test_batch_size: 256
nb_epochs: 100
optimizer: "adam"
lr: 0.0007436
min_lr: 0.000282
num_workers: 4
save_dir: imdb_sequential_ensemble_200
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8866
b2: 0.9989
train_val_split: True
ensemble_size: 50
num_chains: 1
sequential_nb_epochs: 2
sequential_optimizer: adam
sequential_b1: 0.8961
sequential_b2: 0.9994
sequential_lr: 0.002392
sequential_min_lr: 0.0000143
sampler: guided_walk
step_std: 0.02
imbalance: False
normalize: False
competition_mode: False
