dataset_name: imdb
method: ensemble
train_batch_size: 141
test_batch_size: 256
nb_epochs: 100
optimizer: "adam"
lr: 0.0007436
min_lr: 0.000282
num_workers: 4
save_dir: imdb_ensemble_200
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8866
b2: 0.9989
train_val_split: True
ensemble_size: 2
imbalance: False
normalize: False
competition_mode: False
