dataset_name: cifar10
method: sequential_ensemble
train_batch_size: 155
test_batch_size: 256
nb_epochs: 1
optimizer: "adam"
lr: 0.002145
min_lr: 0.0000603
num_workers: 4
save_dir: cifar10_sequential_ensemble_test
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8547
b2: 0.9997
train_val_split: True
ensemble_size: 2
num_chains: 1
sequential_nb_epochs: 1
sequential_optimizer: adam
sequential_b1: 0.8547
sequential_b2: 0.9997
sequential_lr: 0.002145
sequential_min_lr: 0.0001
sampler: guided_walk
step_std: 0.02
imbalance: False
normalize: False
competition_mode: False
