dataset_name: cifar10
method: ensemble
train_batch_size: 155
test_batch_size: 256
nb_epochs: 100
optimizer: "adam"
lr: 0.002145
min_lr: 0.0000603
num_workers: 4
save_dir: cifar10_ensemble_500
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8547
b2: 0.9997
train_val_split: True
ensemble_size: 5
imbalance: False
normalize: False
competition_mode: False
