b1: 0.8547
b2: 0.9997
competition_mode: false
dataset_name: cifar10
ensemble_size: 10
keep_best_weights: true
lr: 0.002145
method: ensemble
min_lr: 6.03e-05
nb_epochs: 100
normalize: false
optimizer: adam
save_dir: cifar10_ensemble_1000
test_batch_size: 256
train_batch_size: 155
train_val_split: true
