b1: 0.8547
b2: 0.9997
competition_mode: false
dataset_name: cifar10
ensemble_size: 2
keep_best_weights: true
lr: 0.002145
method: sequential_ensemble
min_lr: 6.03e-05
nb_epochs: 1
normalize: false
num_chains: 1
optimizer: adam
sampler: guided_walk
save_dir: cifar10_sequential_ensemble_test
sequential_b1: 0.8547
sequential_b2: 0.9997
sequential_lr: 0.002145
sequential_min_lr: 0.0001
sequential_nb_epochs: 1
sequential_optimizer: adam
step_std: 0.02
test_batch_size: 256
train_batch_size: 155
train_val_split: true
