dataset_name: dermamnist_anon
method: ensemble
train_batch_size: 56
test_batch_size: 256
nb_epochs: 100
optimizer: "adam"
lr: 0.0007893
min_lr: 0.0000000387
num_workers: 4
save_dir: dermamnist_anon_ensemble_500
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8774
b2: 0.9989
train_val_split: True
ensemble_size: 5
imbalance: False
normalize: False
competition_mode: False
