b1: 0.8774
b2: 0.9989
competition_mode: false
dataset_name: dermamnist_anon
ensemble_size: 75
keep_best_weights: true
lr: 0.0007893
method: sequential_ensemble
min_lr: 3.87e-08
nb_epochs: 100
normalize: false
num_chains: 2
optimizer: adam
sampler: guided_walk
save_dir: dermamnist_anon_sequential_ensemble_500
sequential_b1: 0.8295
sequential_b2: 0.9944
sequential_lr: 0.001173
sequential_min_lr: 4.47e-05
sequential_nb_epochs: 2
sequential_optimizer: adam
step_std: 0.01
test_batch_size: 256
train_batch_size: 56
train_val_split: true
