b1: 0.8774
b2: 0.9989
competition_mode: false
dataset_name: dermamnist_anon
ensemble_size: 100
keep_best_weights: true
lr: 0.0007893
method: ensemble
min_lr: 3.87e-08
nb_epochs: 100
normalize: false
optimizer: adam
save_dir: dermamnist_anon_ensemble_10000
test_batch_size: 256
train_batch_size: 56
train_val_split: true
