dataset_name: dermamnist_anon
method: sequential_ensemble
train_batch_size: 56
test_batch_size: 256
nb_epochs: 100
optimizer: "adam"
lr: 0.0007893
min_lr: 0.0000000387
num_workers: 4
save_dir: dermamnist_anon_sequential_ensemble_10000
keep_best_weights: True
clip_gradient: False
increase_prior_variance: 1.
b1: 0.8774
b2: 0.9989
train_val_split: True
ensemble_size: 450
num_chains: 10
sequential_nb_epochs: 2
sequential_optimizer: adam
sequential_b1: 0.8295
sequential_b2: 0.9944
sequential_lr: 0.001173
sequential_min_lr: 0.0000447
sampler: guided_walk
step_std: 0.01
imbalance: False
normalize: False
competition_mode: False
